# This file is generated, do not edit!
# Instead see templates/ut_data.template.py and logic/locations.lisp

UT_NAME_MAPPING = {
    "Decryptor: Charge Shot/": 100,
    "Decryptor: Charge Magnet/": 101,
    "Decryptor: Altered Shot/": 102,
    "Decryptor: Charge Grip/": 103,
    "Decryptor: Wall Run/": 104,
    "Decryptor: Spin Dodge/": 105,
    "Decryptor: Heat Resist/": 106,
    "Decryptor: Mental Recovery/": 107,
    "Decryptor: Speed Boost/": 111,
    "Decryptor: Vile Claw/": 112,
    "Decryptor: Piercing Speed/": 113,
    "Decryptor: Golden View/": 114,
    "Decryptor: d#Z 5~qn. P/": 115,
    "Decryptor: Double Shot/": 117,
    "Card 01: Magoom/": 201,
    "Card 02: Ciurivy/": 202,
    "Card 03: Smosey/": 203,
    "Card 04: Wavemoth/": 204,
    "Card 05: Midow/": 205,
    "Card 06: Prittle/": 206,
    "Card 07: Sealime/": 207,
    "Card 08: Toucade/": 208,
    "Card 09: Shaifi/": 209,
    "Card 10: Pengrunt/": 210,
    "Card 13: Drilbas/": 213,
    "Card 14: Jinvell/": 214,
    "Card 15: Royalrose/": 215,
    "Card 16: Rupo/": 216,
    "Card 17: Froesburn/": 217,
    "Card 19: Sherivice/": 219,
    "Card 21: Solatia/": 221,
    "Card 24: Oracle-L/": 224,
    "First Ambush/": 300,
    "Ambush Before Charge Shot/": 301,
    "Power Area Lower Ambush/": 302,
    "Power Area Upper Ambush/": 303,
    "Pre-Spin Dodge Ambush/": 304,
    "Cottospark Ambush/": 305,
    "Block Puzzle Ambush/": 306,
    "Underwater Ambush/": 307,
    "Claw Bounce Ambush/": 308,
    "Floatlands Ambush/": 309,
    "First Health Upgrade/": 400,
    "Pre-Spin Dodge Health Upgrade/": 401,
    "Floatlands Health Upgrade/": 402,
    "Warehouse Entry Health Upgrade/": 403,
    "Phase Upgrade Left of Ship/": 404,
    "Phase Upgrade Outside Griger's Base/": 405,
    "Lower Mountain Phase Upgrade/": 406,
    "Orb A/": 408,
    "Orb B/": 409,
    "Orb C/": 410,
}

tracker_world = {
    "external_pack_key": "ut_pack_path",
    "map_page_maps": "maps/maps.json",
    "map_page_locations": "locations/locations.json",
    "poptracker_name_mapping": UT_NAME_MAPPING
}